"use client";

import { useState, useEffect } from "react";
import { motion } from "framer-motion";
import { RefreshCw, Zap } from "lucide-react";
import { cn } from "@/lib/utils";
import Skeleton from "@/components/Skeleton";

export default function DailyDigest() {
  const [content, setContent] = useState<string>("");
  const [loading, setLoading] = useState(true);
  const [dateStr] = useState(new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }));

  const fetchDigest = async (force = false) => {
    setLoading(true);
    const cached = localStorage.getItem("hp_daily_digest");
    const cachedDate = localStorage.getItem("hp_daily_digest_date");
    const today = new Date().toDateString();

    if (!force && cached && cachedDate === today) {
      setContent(cached);
      setLoading(false);
      return;
    }

    try {
      const res = await fetch("/api/digest", {
        method: "POST",
        body: JSON.stringify({ date: today }),
      });
      const data = await res.json();
      if (data.content) {
        setContent(data.content);
        localStorage.setItem("hp_daily_digest", data.content);
        localStorage.setItem("hp_daily_digest_date", today);
      }
    } catch {
      setContent("ERROR SYNCING DATA. PLEASE RETRY COMMAND.");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchDigest();
  }, []);

  return (
    <motion.div
      initial={{ opacity: 0, scale: 0.98 }}
      animate={{ opacity: 1, scale: 1 }}
      className="bg-[rgba(13,20,36,0.8)] border border-hp-border rounded-sm relative overflow-hidden"
    >
      <div className="bg-hp-surface border-b border-hp-border px-4 py-2 flex items-center justify-between">
        <div className="flex items-center gap-2">
          <Zap size={14} className="text-hp-accent-amber" />
          <h3 className="font-sans font-bold tracking-widest text-xs text-hp-text-primary uppercase">
            {"// DAILY INTEL BRIEF"}
          </h3>
          <span className="font-mono text-[10px] text-hp-text-muted ml-2">{dateStr}</span>
        </div>
        <button 
          onClick={() => fetchDigest(true)}
          disabled={loading}
          className="text-hp-text-muted hover:text-hp-accent-amber transition-colors disabled:opacity-30"
        >
          <RefreshCw size={14} className={cn(loading && "animate-spin")} />
        </button>
      </div>

      <div className="p-6 font-mono text-sm leading-relaxed min-h-[160px] flex flex-col justify-center bg-[rgba(5,8,16,0.4)]">
        {loading ? (
          <div className="flex flex-col gap-3">
            <div className="flex items-center gap-2">
              <span className="w-1.5 h-1.5 bg-hp-accent-amber animate-pulse rounded-full" />
              <p className="text-hp-text-muted animate-pulse uppercase text-[10px] tracking-widest font-bold">SYNCHRONIZING INTEL CHANNEL...</p>
            </div>
            <Skeleton className="h-4 w-[85%]" />
            <Skeleton className="h-4 w-[92%]" />
            <Skeleton className="h-4 w-[78%]" />
            <Skeleton className="h-4 w-[60%]" />
          </div>
        ) : (
          <div className="space-y-2 whitespace-pre-wrap">
            {content.split('\n').map((line, i) => {
              if (!line.trim()) return <div key={i} className="h-2" />;
              const [label, ...rest] = line.split(':');
              if (rest.length > 0) {
                return (
                  <div key={i} className="flex gap-2">
                    <span className="text-hp-accent-amber font-bold shrink-0">{label}:</span>
                    <span className="text-hp-text-primary">{rest.join(':')}</span>
                  </div>
                );
              }
              return <div key={i} className="text-hp-text-primary">{line}</div>;
            })}
            <span className="inline-block w-2.5 h-4 bg-hp-accent-green animate-pulse ml-1" />
          </div>
        )}
      </div>

      <div className="bg-[#050810] px-4 py-1.5 border-t border-hp-border/40 flex justify-between items-center">
        <span className="text-[9px] font-mono text-hp-text-muted lowercase tracking-tighter">Generated by HashPilot AI • Refreshes daily</span>
        <div className="flex gap-4">
          <div className="w-1 h-3 bg-hp-accent-amber/20" />
          <div className="w-1 h-3 bg-hp-accent-amber/40" />
          <div className="w-1 h-3 bg-hp-accent-amber/60" />
        </div>
      </div>
    </motion.div>
  );
}
